### ISSUE TITLE
日本語環境でSwiftUIの `BudouXText` がBudouXパーサーを使用しない

### ISSUE THREAD

**Issue by yuntan** [griffin-stewie/BudouX.swift#22]
<img width="420" alt="スクリーンショット 2023-06-10 11 00 49" src="https://github.com/griffin-stewie/BudouX.swift/assets/574575/11873f77-fd84-40c3-b9f8-326015353949">

環境はmacOS 13.4 Ventura, Xcode 15.0 betaです。

以下再現コードになります。

```
import SwiftUI

import BudouX

struct ContentView: View {
    var body: some View {
        VStack(spacing: 24) {
            BudouXText("ダウンロードありがとうございます！")
                .font(.title)
            
            BudouXText("25がApple Watchにインストールされていることを確認しましょう。")
            
            BudouXText("iPhoneでWatchアプリを開きます。")
            
            BudouXText("25がインストールされていることを確認します。")
            
            BudouXText("このような表示になっている場合は、インストールに時間がかかっています。しばらく待ってみてください。")
        }
        .multilineTextAlignment(.center)
    }
}
```

**Comment by yuntan** [comment]
macOS 13.4 Ventura, Xcode 14.3でも再現しました。

**Comment by yuntan** [comment]
どうやら、 `BudouXText(verbatim:, parser:, condition:)` まで処理が届いていないようです。
<img width="779" alt="スクリーンショット 2023-06-10 15 27 58" src="https://github.com/griffin-stewie/BudouX.swift/assets/574575/1bb91efc-f8b7-4c54-a6ee-2579aa828168">

**Comment by yuntan** [comment]
以下のように修正すると単語の途中で改行されないようになりました。

```
            BudouXText(verbatim: "ダウンロードありがとうございます！") { _ in true }
```

<img width="420" alt="スクリーンショット 2023-06-10 15 36 17" src="https://github.com/griffin-stewie/BudouX.swift/assets/574575/d0e77158-8dca-4511-8069-7ac8877300e5">

（本当は「ダウンロード」「ありがとうございます！」と改行して欲しいところなのですが。）

`defaultBudouXTextCondition` に問題があるようですね。

**Comment by yuntan** [comment]
ロケールが日本語かどうか判断するのであれば

```
    public let defaultBudouXTextCondition: (Set<String>) -> Bool = { naturalLanguagesSupportedByParser in
        guard let lang = Locale.current.language.languageCode?.identifier else {
            return false
        }
        naturalLanguagesSupportedByParser.contains(lang)
    }
```

でいいのかなと思うのですが、どうでしょうか。

**Comment by griffin-stewie** [comment]
@yuntan 
Issue の登録ありがとうございました。

報告された内容をこちらで検証してみました。

「日本語環境でSwiftUIの BudouXText がBudouXパーサーを使用しない」という Issue に対する現状の私の結論としては、

動作環境（OS）の設定が日本語環境であっても、アプリケーション側が日本語に対応していない場合は、BudouX.swift としては何もせずに `Text` を使うのが想定動作でありバグではない

となります。

## 詳細説明

まず、現状の [BudouX.swift](https://github.com/griffin-stewie/BudouX.swift) が提供する `BudouXText` の想定仕様として以下のようになっています。

- オリジナル実装である [BudouX](https://github.com/google/budoux) がサポートしている言語をサポートしているアプリケーションであれば、BudouX によって改行位置がより言語的に自然になるように前処理を行う
- アプリケーション側がサポートしている言語が、オリジナル実装である [BudouX](https://github.com/google/budoux) がサポートしていない言語であった場合は、 [BudouX.swift](https://github.com/griffin-stewie/BudouX.swift) は介入せず、SwiftUI 標準である `Text` を使う

重要なポイントは「アプリケーションがサポートしている言語かどうか」です。OS の設定や入力として与えられた文字列がどの言語かは関係ありません。

私の認識では、`Locale.current` はシステムの設定 + アプリがサポートしている言語 を加味した結果の Locale インスタンスが返されるものです。

一般的な日本語環境の設定（ja_JP）のマシン上で、Xcode のテンプレートから作成しただけのアプリケーションを動作させると、`Locale.current.language.languageCode` は `en` になっていると思われます。
`developmentRegion` を [iOSアプリのローカライズとローカリゼーションのデバッグ - 開発言語の変更、ストーリーボードと文字列のローカライズ、ローカライズされていない文字列の特定とデバッグ - Qiita⁤](https://qiita.com/mashunzhe/items/86200a5c03817497ac29) を参考に `ja` に変更した場合は、`Locale.current.language.languageCode` は `ja` になっていると思われます。
当然ながら、Localizable.strings を追加し、日本語にローカライズした場合には`Locale.current.language.languageCode` は `ja` になっているはずです。

このような仕組みになっているため、言語の判定処理に `Locale.current` という一見すると素直な実装を意図的に使っていません。ライブラリ側に言語判定をするためだけに存在している Localizable.strings を用意して "net.cyan-stivy.budoux-swift.LocalizationFinder.Key" で identifier が取得できるようにしています。

**Comment by griffin-stewie** [comment]
>（本当は「ダウンロード」「ありがとうございます！」と改行して欲しいところなのですが。）

@yuntan 

こちらに関しては オリジナル実装である [BudouX](https://github.com/google/budoux) が対応してくれてたようなので、BudouX.swift 側に同梱させている学習モデルも近いうちアップデートしたいと思います。

フィードバックありがとうございました。

**Comment by yuntan** [comment]
詳細にご説明いただきありがとうございます。

> 重要なポイントは「アプリケーションがサポートしている言語かどうか」です。OS の設定や入力として与えられた文字列がどの言語かは関係ありません。

OSの言語設定：日本語  
アプリの対応言語：英語  
文字列：日本語  
の場合は、 `Text` にフォールバックするということで理解しました。

また、ProjectのLocalizationにJapaneseを追加し、Localizable.stringsを追加しLocalizationをJapaneseに設定した場合に、BudouXが適用されることを確認しました。

上記については理解できたのですが、 `Locale.current` を使わない理由については理解できなかったです。 `Locale.current` がOSの言語設定を加味しているため使っていないということでしょうか？

> こちらに関しては オリジナル実装である [BudouX](https://github.com/google/budoux) が対応してくれてたようなので、BudouX.swift 側に同梱させている学習モデルも近いうちアップデートしたいと思います。
>
> フィードバックありがとうございました。

少しでもお役に立てたなら幸いです。

**Comment by griffin-stewie** [comment]
@yuntan 
Locale.current には想定外の挙動が多く Qiita 等に記事がいくつも上がっているのでそちらを参照いただくのが良いかと思います。

例えば、以下の記事にも BudouX.swift が採用している方法が紹介されており現状のベストプラクティスというのが分かっていただけるかと思います。

[iOSの言語設定を取得するベストプラクティス(Swift) - Qiita](https://qiita.com/uhooi/items/a9c9d8b923005028ce4e)

**Comment by yuntan** [comment]
ありがとうございます。理解しました。

**Comment by griffin-stewie** [comment]
@yuntan 
[「ありがとう」のハンドリングが改善されたモデル](https://github.com/google/budoux/pull/154) を同梱した [v0.8.0](https://github.com/griffin-stewie/BudouX.swift/releases/tag/v0.8.0) をリリースしました。


```sh
# 古いバージョンの動作
❯ budoux-swift -l ja "ダウンロードありがとうございます！" 
ダウンロードありが
とうございます！

# 新しいバージョンの動作
❯ ./budoux-swift -l ja "ダウンロードありがとうございます！"              
ダウンロード
ありがとう
ございます！
```
